### ISSUE TITLE
rake db:migrate apparently fails when setting up from a fresh checkout

### ISSUE THREAD

**Issue by kltm** [pubannotation/pubannotation#2]
I can attempt to try and tease out what the issue is on my fork and float a PR, but I thought it might be useful to report first.

When attempting to run the PubAnnotation code locally for development on a local Ubuntu 16.04 LTS AWS machine, I run into the following error midway through ```rake db:migrate```:

```
==  RenameAnnsetsToProjects: migrating ========================================
-- rename_table(:annsets, :projects)
   -> 0.0028s
-- add_index(:projects, :name, {:unique=>true})
   -> 0.0048s
-- remove_index(:annsets_docs, [:annset_id, :doc_id])
   -> 0.0019s
-- rename_table(:annsets_docs, :docs_projects)
   -> 0.0025s
-- rename_column(:docs_projects, :annset_id, :project_id)
   -> 0.0003s
-- add_index(:docs_projects, [:project_id, :doc_id], {:unique=>true})
   -> 0.0024s
-- remove_index(:catanns, :annset_id)
   -> 0.0020s
-- rename_column(:catanns, :annset_id, :project_id)
   -> 0.0003s
-- add_index(:catanns, :project_id)
   -> 0.0026s
-- remove_index(:insanns, :annset_id)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

Index name 'index_insanns_on_annset_id' on table 'insanns' does not exist
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:587:in `index_name_for_remove'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/schema_statements.rb:366:in `remove_index'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:466:in `block in method_missing'
```

I've been documenting the setup as I go. The complete setup and steps that I'm using are:

```
### Installation Ubuntu 16.04 LTS
### This setup assumes that we will install ruby gems globally (as root).

## Setup.
sudo apt-get -u install build-essential ruby-dev zlib1g-dev libxml2-dev libpq-dev

## Get the code situated
mkdir -p local/src/git
git clone https://github.com/pubannotation/pubannotation.git
cd pubannotation

## Install rails/app
bundle install

## Get a postgres instance to work against. First install.
sudo apt-get -u install postgresql
## Setup password for user.
sudo -u postgres psql postgres
\password postgres
<PASSWORD>
## Create db with user.
sudo -u postgres createdb pubannotation
sudo -u postgres createdb pubannotation_test
## Test connection.
psql -W -U postgres -h localhost pubannotation

## Configure rails.
[Add "username",  "password", and "host" (localhost) to entries in config/database.yml.]
rake
rake db:migrate ## ERROR
#rails s
rails s -e development -p 8080
```

Feel free to add this to any installation documentation that you may have.

**Comment by kltm** [comment]
On the invitation of @jdkim, I'm trying again as there have been fixes since the last time.
Setting up again, this time on a fresh ubuntu:16.04 docker image, there have been a few changes to the script above; in no particular order:
```
## Need a JS environment:
apt-get -u install nodejs

## Need to create a "root" role; maybe while testing above:
CREATE USER root WITH PASSWORD '<PASSWORD>';
```

**Comment by kltm** [comment]
The `rake db:migrate` command still fails, but differently:
```
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
[DEPRECATION] `last_comment` is deprecated.  Please use `last_description` instead.
-- create_table("annotators")
   -> 0.9806s
-- add_index(:annotators, :abbrev, {:unique=>:true})
   -> 0.0448s
-- add_index("annotators", ["user_id"], {:name=>"index_annotators_on_user_id"})
   -> 0.0478s
-- create_table("associate_maintainers")
   -> 0.0493s
-- add_index(:associate_maintainers, :project_id)
   -> 0.0467s
-- add_index(:associate_maintainers, :user_id)
   -> 0.0480s
-- create_table("delayed_jobs")
   -> 0.0909s
-- add_index(:delayed_jobs, [:priority, :run_at])
   -> 0.0701s
-- create_table("denotations")
   -> 0.0512s
-- add_index(:denotations, :doc_id)
   -> 0.0406s
-- add_index(:denotations, :project_id)
   -> 0.0569s
-- create_table("docs")
   -> 0.2474s
-- add_index(:docs, :projects_count)
   -> 0.0651s
-- add_index(:docs, :serial)
   -> 0.0525s
-- add_index(:docs, :sourcedb)
   -> 0.0566s
-- add_index(:docs, :sourceid)
   -> 0.0563s
-- create_table("docs_projects", {:id=>false})
   -> 0.0009s
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

uninitialized constant CreateTables::DocsProject
/tmp/pubannotation/db/migrate/20160706062835_create_tables.rb:130:in `<class:CreateTables>'
/tmp/pubannotation/db/migrate/20160706062835_create_tables.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:537:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:533:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:775:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:719:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:700:in `each'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:570:in `up'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:551:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
NameError: uninitialized constant CreateTables::DocsProject
/tmp/pubannotation/db/migrate/20160706062835_create_tables.rb:130:in `<class:CreateTables>'
/tmp/pubannotation/db/migrate/20160706062835_create_tables.rb:1:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:537:in `load_migration'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:533:in `migration'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:528:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:720:in `block (2 levels) in migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:775:in `block in ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/connection_adapters/abstract/database_statements.rb:192:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/transactions.rb:208:in `transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:775:in `ddl_transaction'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:719:in `block in migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:700:in `each'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:700:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:570:in `up'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/migration.rb:551:in `migrate'
/var/lib/gems/2.3.0/gems/activerecord-3.2.22.2/lib/active_record/railties/databases.rake:193:in `block (2 levels) in <top (required)>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by kltm** [comment]
To self: make and push a Docker image to reproduce error?
